#!/bin/bash

NAME=$0

if [ -L $NAME ]; then
        NAME=`readlink -f $NAME`
fi

CRUSH=`dirname $NAME`

source $CRUSH/wrapper.sh

#JAVA=/usr/java/latest/bin/java
#CLASSPATH="$CRUSH/src:$CRUSH/fits.jar:$CRUSH/bin"

$JAVA $JAVAOPTS -classpath $CLASSPATH test.FitsDeferredTest $* 
