/*******************************************************************************
 * Copyright (c) 2013 Attila Kovacs <attila[AT]sigmyne.com>.
 * All rights reserved. 
 * 
 * This file is part of jnum.
 * 
 *     jnum is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 * 
 *     jnum is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with jnum.  If not, see <http://www.gnu.org/licenses/>.
 * 
 * Contributors:
 *     Attila Kovacs <attila[AT]sigmyne.com> - initial API and implementation
 ******************************************************************************/
package jnum.util;

import java.util.Random;


/**
 * A Random generator with a backing buffer for reducing correlations between calls.
 * 
 * 
 * BufferedRandom keeps a collection of Random numbers and bits, generated by the {@link java.util.Random}, from which it
 * randomly picks a value upon request. At the same time, a new random number is buffered in that same slot. The buffering
 * of random numbers is expected to reduce correlations between calls.
 */
public class BufferedRandom extends Random {

    private static final long serialVersionUID = -8696559579537431957L;

	private int[] buffer;
	
	/**
	 * Instantiates a new buffered random generator with a default number of buffered elements.
	 */
	public BufferedRandom() {
		this(100);
	}
	
	/**
	 * Instantiates a new buffered random generator with the specified number of buffered random numbers.
	 *
	 * @param size the number of random numbers buffered.
	 */
	public BufferedRandom(int size) {
		buffer = new int[size];
		for(int i=0; i<size; i++) buffer[i] = super.next(32);	
	}
	
	/**
	 * Use the current timestamp for seeding the random generator.
	 */
	public void seedNow() {
		setSeed(System.currentTimeMillis());
	}

	@Override
	public int next(int bits) {
		final int mask = (int) ((1L<<bits) - 1L);
	    
		/* Choose a slot from which to pick a random number */
	    final int i = (int) (buffer.length * Math.random());
		final int value = buffer[i] & mask;
		
		/* Replace the used bits with a new value */
		buffer[i] &= ~mask;
		buffer[i] |= super.next(bits);
		
		return value;
	}

}
